### ISSUE TITLE
无法获取通过第三方Yggdrasil API登陆的玩家的头颅

### ISSUE THREAD

**Issue by Nixieboluo** [YggdrasilOfficialProxy/YggdrasilOfficialProxy#13]
当开启正版优先时，无法在获取头颅时使用第三方Yggdrasil API玩家的皮肤(通过玩家名)

也希望支持当玩家同名时强制请求正版皮肤或第三方皮肤的方法(通过玩家名)

**Comment by Karlatemp** [comment]
https://github.com/yushijinhun/authlib-injector/wiki/%E5%9C%A8-Minecraft-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E4%BD%BF%E7%94%A8-authlib-injector#%E8%B0%83%E7%94%A8-mojang-%E7%9A%AE%E8%82%A4

**Comment by Nixieboluo** [comment]
目前的情况是
玩家使用第三方验证登陆时 可以正常显示所有皮肤
但玩家若使用Mojang验证 则只能看见正版玩家的皮肤
请问有解决办法吗
