### ISSUE TITLE
使用geyser时出现错误

### ISSUE THREAD

**Issue by qingyiwebt** [YggdrasilOfficialProxy/YggdrasilOfficialProxy#14]
![Screenshot_2020-11-13-13-50-52-013_mark via](https://user-images.githubusercontent.com/42484761/99030046-69d8f080-25b7-11eb-8374-f00f618a9f27.jpg)
使用yop(agent模式)+spigot+geyser(插件模式)时，使用geyser登录，服务端报异常，如上图。

以下为配置文件内容：
![Screenshot_2020-11-13-13-53-42-861_bin mt plus](https://user-images.githubusercontent.com/42484761/99030154-b0c6e600-25b7-11eb-8df4-ce0b9f10c52d.jpg)

以下为启动的附加参数：
```
-XX:+UseFastAccessorMethods -XX:+UseConcMarkSweepGC -XX:ParallelGCThreads=2 -XX:+AggressiveOpts -XX:+UseCompressedOops -javaagent:yop.jar
```

**Comment by qingyiwebt** [comment]
注：使用java版登录时无问题，但是使用geyser+基岩版登录就有问题

**Comment by Karlatemp** [comment]
YggdrasilOfficialProxy设计之初并没有考虑登录的情况, 因为处理二次登录不属于YOP的主要任务

**Comment by qingyiwebt** [comment]
最后我魔改了mcauthlib的源代码，并重新编译了geyser解决了问题
