### ISSUE TITLE
[PROBLEM] 正版和yggdrasil的用户UUID一致

### ISSUE THREAD

**Issue by pianwan** [YggdrasilOfficialProxy/YggdrasilOfficialProxy#16]
**我已确认我使用的版本是收到支持的v2.x**

**我已经确认出现服务器宕机等无法进入服务器的情况时 https://status.mojang.com/check 显示正常 且 YOP 代理配置无误**

错误说明:
环境:
paper-1.16.4-364
YggdrasilOfficialProxy-2.1.3-paperclip
authlib-injector-1.1.34
yggdrasil API 使用的是LittleSkin的
无任何插件
除了修改api="https://mcskin.littleservice.cn/api/yggdrasil"无其他任何配置文件的修改

错误复现步骤:
任意一个玩家，使用littleskin帐号登陆或者使用正版登陆后，同名的uuid都保持不变，即再用另一种方式登陆，帐号和原来保持一致，不能同时在线。

错误日志:
```text
(如果有错误日志, 请粘贴到此处, 并且避免使用pastebin)
```
![image](https://user-images.githubusercontent.com/13903138/103449946-46ded900-4cea-11eb-901e-5d02b4d444f6.png)
![image](https://user-images.githubusercontent.com/13903138/103449950-5b22d600-4cea-11eb-9295-358546613f30.png)
可以看到我的UUID一直都是fd85ccba-afd8-4f92-b21c-29ef700ed2a5，不论是正版登陆还是Lttleskin yggdrasil

YggdrasilOfficialProxy配置
```hocon
# The yggdrasil api root
api="https://mcskin.littleservice.cn/api/yggdrasil"
# The location of YggdrasilInjector
# @see https://github.com/yushijinhun/authlib-injector/
authlib-injector="./authlib-injector-1.1.34.jar"
# IMPORTANT: Set this value to `true`!
edited=true
# When access multiple apis. Use official api first.
official-first=false
# Proxy settings
proxy {
    just-example-for-http {
        type=http
        url="http://localhost/proxy"
    }
    # The proxy of official connecting
    official {
        host=localhost
        port=1080
        type=direct
    }
    # The proxy of yggdrasil connecting
    yggdrasil {
        type=direct
    }
}
# The server binding actions.
server {
    host="0.0.0.0"
    port=30015
}```

服务器启动命令行
```script shell
java -Xmx4G -Xms1G -javaagent:YggdrasilOfficialProxy-2.1.3-paperclip.jar -jar paperclip.jar
```

**Comment by Karlatemp** [comment]
同名玩家进入服务器后，验证接口会有一个缓存，由于YOP的工作原理以及其限制，需要等这个缓存过期后才能正常

**Comment by pianwan** [comment]
> 同名玩家进入服务器后，验证接口会有一个缓存，由于YOP的工作原理以及其限制，遇到等这个缓存过期后才能正常

但是这样会有一个很大的问题，正版玩家的帐号,可以由其他玩家注册yggdrasil同名帐号后无密码登陆

**Comment by pianwan** [comment]
> 同名玩家进入服务器后，验证接口会有一个缓存，由于YOP的工作原理以及其限制，需要等这个缓存过期后才能正常

而且，即使重启代理，再使用yggdrasilAPI的帐号登陆，uuid也是保持不变，始终是正版的UUID。

**Comment by pianwan** [comment]
已经解决了，是littleskin的锅
