### ISSUE TITLE
请更新依赖的authlib注入器版本

### ISSUE THREAD

**Issue by Huaxidesu** [YggdrasilOfficialProxy/YggdrasilOfficialProxy#17]
问题地址
https://github.com/IzzelAliz/Arclight/issues/136#event-4246785008

**Comment by Karlatemp** [comment]
authlib injector是需要你自己下的不是yop自动下的，自己更新去

**Comment by Huaxidesu** [comment]
> authlibjecter是需要你自己下的不是yop自动下的，自己更新去

我使用的确实是最新版authlib
我使用的是1.1.34，构建站里的也是1.1.34但是我用螺端后不使用-Djava.util.logging.manager=io.izzel.arclight.common.mod.util.log.ArclightLazyLogManager
仍然会炸掉所有插件
