### ISSUE TITLE
是否正常支持Java16

### ISSUE THREAD

**Issue by NiceDavid07115** [YggdrasilOfficialProxy/YggdrasilOfficialProxy#21]
服务端更新到Java16后，无论正版还是外置登录玩家，进入服务器通讯加密后显示“认证服务器处于宕机状态中，请稍后再试，抱歉！”而同样的配置在Java8环境下没有此问题。
YOP2.3.0配置如下：
.# CDN settings
CDN {
    enable=false
    origin="CDN origin link"
}
.# The yggdrasil api root
api="https://mcskin.orecraft.cn/api/yggdrasil"
.# The location of YggdrasilInjector
.# @see https://github.com/yushijinhun/authlib-injector/
authlib-injector="/root/mc/survival.5/server/authlib-injector-1.1.35.jar"
.# IMPORTANT: Set this value to `true`!
edited=true
.# When access multiple apis. Use official api first.
official-first=true
.# Proxy settings
proxy {
    just-example-for-http {
        type=http
        url="http://localhost/proxy"
    }
    .# Example for socks proxy
    just-example-for-socks {
        host=localhost
        port=1080
        type=socks
    }
   . # Example for socks proxy with authentication
    just-example-for-socks-with-authentication {
        host=localhost
        password=password
        port=1080
        type=socks
        username=username
    }
    .# The proxy of official connecting
    official {
        type=direct
    }
    .# The proxy of yggdrasil connecting
    yggdrasil {
        type=direct
    }
}
.# The server binding actions.
server {
    host="0.0.0.0"
    port=36520
}
出现报错如下：[Server] [20:51:58] [User Authenticator #1/INFO]: Disconnecting com.mojang.authlib.GameProfile@3b26da3a[id=<null>,name=NiceDavidVeiz,properties={},legacy=false] (/120.239.173.127:28662): Authentication servers are down. Please try again later, sorry!
[Server] [20:51:58] [User Authenticator #1/ERROR]: Couldn't verify username because servers are unavailable
[Server] [20:51:58] [Server thread/INFO]: com.mojang.authlib.GameProfile@3b26da3a[id=<null>,name=NiceDavidVeiz,properties={},legacy=false] (/120.239.173.127:28662) lost connection: Authentication servers are down. Please try again later, sorry!
——————————————————————————————————————————————————
[root@VM-8-10-centos server]# java -jar YggdrasilOfficialProxy-2.3.0-proxy.jar
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[YggdrasilOfficialProxy] Server running on 0.0.0.0:36520
[YggdrasilOfficialProxy] [ INFO] Autoreload is disabled because the development mode is off.
[YggdrasilOfficialProxy] [ INFO] Responding at http://0.0.0.0:36520
[YggdrasilOfficialProxy] [ WARN] A exception in reading network.

**Comment by Hai-tun** [comment]
@NiceDavid07115 感谢支持~
这个问题并不是由于 Java 16 造成的
是由于高版本 ktor 限制了纤程中调用阻塞IO导致
当前已修复 相关 issue #22
令已于 Java 16.0.1 完成测试  运行正常 =w=
