### ISSUE TITLE
支持多个Yggdrasil服务器

### ISSUE THREAD

**Issue by vlssu** [YggdrasilOfficialProxy/YggdrasilOfficialProxy#29]
**我已确认目前使用的是受到支持的v2.x版本**

此特性可以用于:
可以让多个认证服务器进入服务器，给不同认证服务器的玩家进入一个服务器
这样可以方便服务器联谊

**Comment by Becods** [comment]
看看[CaaMoe/MultiLogin](https://github.com/CaaMoe/MultiLogin)吧

**Comment by MuelsyseKen** [comment]
> 看看[CaaMoe/MultiLogin](https://github.com/CaaMoe/MultiLogin)吧

时隔1年我也不知道能不能再重新开启这个Issue，最近才发现一个很严重的问题，就差不多是这样的
整合包是Forge 1.19.2 ，使用 Mohist 开启服务器，然后装载MultiLogin插件，结果报错无法运行，尝试通过外置的方法进行支持Yggdrasil，但外置的又只能支持一个服务器。
那我们换个思路，用WaterFall，听说支持Forge了，哎，您猜怎么着，开始有人反馈1.16.5以上的搞不了，出现各类的错误，好了现在问题来了。
外置的只支持一个Yggdrasil，用Multilogin吧，Mohist不支持，那用WaterFall加多一层吧，WaterFall对Mohist不支持，合着Mohist是孤岛对吧（
回归正传，我还是希望支持多个Yggdrasil服务器 ，这个Issue也差不多2年了捏。

PS：我试过lightFall，也依然不行。

掘墓（
