### ISSUE TITLE
Colormotd-reremake异常

### ISSUE THREAD

**Issue by CECoffee** [YggdrasilOfficialProxy/YggdrasilOfficialProxy#4]
此混合登录导致colormotd-reremake无法使用。外部在获取motd时，后台会出现大量报错，且该现象较普遍，在papermc1.15.2中可复现。

**Comment by Karlatemp** [comment]
可以的话，请将刷屏部分错误粘贴过来

**Comment by CECoffee** [comment]
报错：https://paste.ubuntu.com/p/TYWnCrCztz

**Comment by CECoffee** [comment]
换用Colormotd后正常
